-- Legends of Retro Web v0.1.8
-- Adds the Game of the Month timer and its own separate leaderboard/submissions.
-- Safe to run after 001_game_of_the_month.sql. Does NOT alter main challenge submissions/results.

alter table public.game_of_the_month
  add column if not exists starts_at timestamptz,
  add column if not exists ends_at timestamptz,
  add column if not exists timer_status text not null default 'stopped',
  add column if not exists paused_remaining_ms bigint;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'game_of_the_month_timer_status_check'
      and conrelid = 'public.game_of_the_month'::regclass
  ) then
    alter table public.game_of_the_month
      add constraint game_of_the_month_timer_status_check
      check (timer_status in ('stopped','running','ended'));
  end if;
end $$;

create table if not exists public.game_of_the_month_submissions (
  id bigint generated by default as identity primary key,
  game_of_the_month_id bigint not null references public.game_of_the_month(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  time_ms bigint not null check (time_ms > 0),
  proof_url text,
  submitted_at timestamptz not null default now()
);

create index if not exists gotm_submissions_month_idx
  on public.game_of_the_month_submissions(game_of_the_month_id);
create index if not exists gotm_submissions_user_idx
  on public.game_of_the_month_submissions(user_id);
create index if not exists gotm_submissions_time_idx
  on public.game_of_the_month_submissions(game_of_the_month_id, time_ms);

alter table public.game_of_the_month_submissions enable row level security;

grant select, insert, update, delete on table public.game_of_the_month_submissions to authenticated;
grant usage, select on sequence public.game_of_the_month_submissions_id_seq to authenticated;

drop policy if exists "GOTM submissions authenticated read" on public.game_of_the_month_submissions;
create policy "GOTM submissions authenticated read"
on public.game_of_the_month_submissions
for select to authenticated
using (true);

drop policy if exists "GOTM runners insert own time" on public.game_of_the_month_submissions;
create policy "GOTM runners insert own time"
on public.game_of_the_month_submissions
for insert to authenticated
with check (
  user_id = (select auth.uid())
  and exists (
    select 1 from public.game_of_the_month g
    where g.id = game_of_the_month_id
      and g.active = true
      and g.timer_status = 'running'
      and g.ends_at is not null
      and g.ends_at > now()
  )
);

drop policy if exists "GOTM runners delete own time" on public.game_of_the_month_submissions;
create policy "GOTM runners delete own time"
on public.game_of_the_month_submissions
for delete to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "GOTM admin update submissions" on public.game_of_the_month_submissions;
create policy "GOTM admin update submissions"
on public.game_of_the_month_submissions
for update to authenticated
using (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role='Admin'))
with check (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role='Admin'));

drop policy if exists "GOTM admin delete submissions" on public.game_of_the_month_submissions;
create policy "GOTM admin delete submissions"
on public.game_of_the_month_submissions
for delete to authenticated
using (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role='Admin'));
