import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4'

const SUPABASE_URL = 'https://bbyejaouyjcihhbgokgn.supabase.co'
const SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_LSji76JlF7FEKgIIvtn0UQ_fXNk3BQF'

const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: { autoRefreshToken: true, persistSession: true, detectSessionInUrl: true },
})

const state = {
  session:null, profile:null, tab:'challenge', challenge:null, challenges:[], games:[], submissions:[], members:[], profiles:[], champions:[], monthly:null, monthlySubmissions:[], monthlyTableMissing:false, monthlySetupMissing:false,
}
const app=document.querySelector('#app')
const escapeHtml=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))
const statusName=s=>{const x=String(s||'').toLowerCase();return x==='active'?'Active':(x==='reveal'||x==='locked')?'Reveal':(x==='complete'||x==='completed')?'Complete':'Draft'}
const fmtTime=ms=>{if(ms==null)return '—';const t=Math.floor(ms/1000),milli=ms%1000,h=Math.floor(t/3600),m=Math.floor((t%3600)/60),s=t%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(milli).padStart(3,'0')}`:`${m}:${String(s).padStart(2,'0')}.${String(milli).padStart(3,'0')}`}
function parseTime(v){const p=v.trim().split(':');let h=0,m=0,s=0;if(p.length===2){m=Number(p[0]);s=Number(p[1])}else if(p.length===3){h=Number(p[0]);m=Number(p[1]);s=Number(p[2])}else throw Error('Use M:SS.mmm or H:MM:SS.mmm');if(![h,m,s].every(Number.isFinite)||h<0||m<0||s<0||s>=60)throw Error('Invalid time');return Math.round((h*3600+m*60+s)*1000)}
let authWork=Promise.resolve(), countdownHandle=null
function withTimeout(promise,ms,label){let timer;const timeout=new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error(`${label} timed out after ${Math.round(ms/1000)} seconds.`)),ms)});return Promise.race([promise,timeout]).finally(()=>clearTimeout(timer))}
async function loadSignedInApp(){splash('Loading Legends…');try{await withTimeout(loadProfile(),12000,'Runner profile');await withTimeout(loadAll(),18000,'Legends data');render()}catch(err){console.error(err);app.innerHTML=`<div class="loginPage"><div class="errorBox"><h2>LEGENDS WEB ERROR</h2><p>${escapeHtml(err.message||String(err))}</p><button class="primary" id="retryLoad">TRY AGAIN</button><button class="ghost" id="errorLogout">LOG OUT</button></div></div>`;document.querySelector('#retryLoad').onclick=loadSignedInApp;document.querySelector('#errorLogout').onclick=()=>supabase.auth.signOut()}}
async function boot(){supabase.auth.onAuthStateChange((event,session)=>{state.session=session;authWork=authWork.then(async()=>{await new Promise(r=>setTimeout(r,0));if(event==='PASSWORD_RECOVERY'&&session){const pw=prompt('Enter your new Legends password (6+ characters)');if(pw&&pw.length>=6){const {error}=await supabase.auth.updateUser({password:pw});alert(error?error.message:'Password updated.')} }if(session)await loadSignedInApp();else{state.profile=null;render()}}).catch(console.error)});const {data,error}=await withTimeout(supabase.auth.getSession(),10000,'Session check');if(error)throw error;state.session=data.session;if(state.session)await loadSignedInApp();else render()}
async function loadProfile(){const {data,error}=await supabase.from('profiles').select('id,username,role,disabled').eq('id',state.session.user.id).maybeSingle();if(error)throw error;state.profile=data}
async function loadAll(){
  const {data:chs,error:ce}=await supabase.from('challenges').select('id,name,status,created_at,revealed_at,started_at,ends_at,completed_at').order('id',{ascending:false});
  if(ce)throw ce;
  state.challenges=chs||[];
  state.challenge=state.challenges.find(c=>['Active','Reveal','Draft'].includes(statusName(c.status)))||state.challenges[0]||null;
  const {data:allProfiles,error:pe}=await supabase.from('profiles').select('id,username,role,disabled').order('username');
  if(pe)throw pe;
  state.profiles=allProfiles||[];
  if(!state.challenge){state.games=[];state.submissions=[];state.members=[];state.champions=[]}
  else{
    const cid=state.challenge.id;
    const [g,s,m,cp]=await Promise.all([
      supabase.from('challenge_games').select('*').eq('challenge_id',cid).order('slot'),
      supabase.from('submissions').select('id,challenge_id,challenge_game_id,user_id,time_ms,proof_url,submitted_at').eq('challenge_id',cid),
      supabase.from('challenge_members').select('challenge_id,user_id,joined_at').eq('challenge_id',cid),
      supabase.from('champions').select('challenge_id,user_id,total_time_ms,awarded_at').eq('challenge_id',cid)
    ]);
    const err=[g.error,s.error,m.error,cp.error].find(Boolean);if(err)throw err;
    state.games=g.data||[];state.submissions=s.data||[];state.members=m.data||[];state.champions=cp.data||[];
  }
  const gotm=await supabase.from('game_of_the_month').select('*').eq('active',true).order('month_key',{ascending:false}).limit(1).maybeSingle();
  state.monthlyTableMissing=!!gotm.error;
  state.monthly=gotm.error?null:gotm.data;
  state.monthlySubmissions=[];state.monthlySetupMissing=false;
  if(state.monthly){
    const ms=await supabase.from('game_of_the_month_submissions').select('id,game_of_the_month_id,user_id,time_ms,proof_url,submitted_at').eq('game_of_the_month_id',state.monthly.id);
    if(ms.error)state.monthlySetupMissing=true;else state.monthlySubmissions=ms.data||[];
  }
}
function standings(){const pmap=new Map(state.profiles.map(p=>[p.id,p.username])),ids=new Set([...state.members.map(m=>m.user_id),...state.submissions.map(s=>s.user_id)]),rows=[];for(const uid of ids){const times=new Map();for(const g of state.games){const vals=state.submissions.filter(s=>s.user_id===uid&&s.challenge_game_id===g.id).map(s=>s.time_ms);if(vals.length)times.set(g.id,Math.min(...vals))}const done=times.size,total=state.games.length&&done===state.games.length?[...times.values()].reduce((a,b)=>a+b,0):null;rows.push({uid,username:pmap.get(uid)||'Runner',done,total,times})}return rows.sort((a,b)=>a.total!=null&&b.total!=null?a.total-b.total:a.total!=null?-1:b.total!=null?1:b.done-a.done||a.username.localeCompare(b.username))}
function render(){if(countdownHandle){clearInterval(countdownHandle);countdownHandle=null}if(!state.session)return renderLogin();if(!state.profile)return splash('Loading runner profile…');if(state.profile.disabled)return splash('This Legends account is disabled.');const admin=state.profile.role==='Admin';app.innerHTML=`<div class="appShell"><aside class="sidebar"><img src="/legends-logo.png" class="sideLogo"><nav>${navButton('challenge','◆','Active Challenge')}${navButton('overall','▥','Overall Leaderboard')}${navButton('games','▦','Game Leaderboards')}${navButton('monthly','★','Game of the Month')}${navButton('champions','♛','Champions')}${navButton('profile','●','Runner Profile')}${navButton('history','◷','Challenge History')}${admin?navButton('creator','＋','Challenge Creator'):''}${admin?navButton('reveal','◇','Reveal Control'):''}${admin?navButton('admin','⚙','Admin'):''}</nav><div class="signedIn">SIGNED IN AS<br><b>${escapeHtml(state.profile.username)}</b></div></aside><main class="main"><header class="topbar"><div><span class="eyebrow">LEGENDS OF RETRO</span> <b>${escapeHtml(state.profile.role).toUpperCase()}</b></div><button class="ghost" id="logout">LOG OUT</button></header><div id="page"></div></main></div>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()});document.querySelector('#logout').onclick=()=>supabase.auth.signOut();const page=document.querySelector('#page');if(state.tab==='challenge')page.innerHTML=challengePage();if(state.tab==='overall')page.innerHTML=overallPage();if(state.tab==='games')page.innerHTML=gamesPage();if(state.tab==='monthly')page.innerHTML=monthlyPage();if(state.tab==='champions')page.innerHTML=championsPage();if(state.tab==='profile')page.innerHTML=profilePage();if(state.tab==='history')page.innerHTML=historyPage();if(state.tab==='creator'&&admin)page.innerHTML=creatorPage();if(state.tab==='reveal'&&admin)page.innerHTML=revealPage();if(state.tab==='admin'&&admin)page.innerHTML=adminPage();wirePage()}
function navButton(id,icon,label){return `<button class="nav ${state.tab===id?'active':''}" data-tab="${id}"><span>${icon}</span>${label}</button>`}
function title(t,s){return `<div class="pageTitle"><div class="eyebrow">LEGENDS OF RETRO</div><h1>${t}</h1><p>${s}</p></div>`}
function splash(label){app.innerHTML=`<div class="splash"><img src="/legends-logo.png"><h2>${escapeHtml(label)}</h2></div>`}
function renderLogin(){
  app.innerHTML=`<div class="loginPage"><div class="loginCard"><img src="/legends-logo.png" class="loginLogo"><h1>ENTER LEGENDS</h1><p>Log in or create a free Runner account.</p><div class="authTabs"><button class="primary" id="showLogin">LOG IN</button><button class="outline" id="showSignup">CREATE RUNNER ACCOUNT</button></div><div id="authPanel"></div></div></div>`
  const panel=document.querySelector('#authPanel')
  const login=()=>{panel.innerHTML=`<form id="loginForm" class="formStack"><input type="email" id="email" placeholder="Email" required><input type="password" id="password" placeholder="Password" required><button class="primary">LOG IN</button><button type="button" class="linkButton" id="forgotPassword">FORGOT PASSWORD?</button><div id="loginMsg" class="error"></div></form>`;document.querySelector('#loginForm').onsubmit=async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('.primary');btn.disabled=true;btn.textContent='SIGNING IN…';const {error}=await supabase.auth.signInWithPassword({email:document.querySelector('#email').value.trim(),password:document.querySelector('#password').value});if(error){document.querySelector('#loginMsg').textContent=error.message;btn.disabled=false;btn.textContent='LOG IN'}};document.querySelector('#forgotPassword').onclick=forgot}
  const signup=()=>{panel.innerHTML=`<form id="signupForm" class="formStack"><input type="text" id="runnerName" placeholder="Runner name" maxlength="40" required><input type="email" id="signupEmail" placeholder="Email" required><input type="password" id="signupPassword" placeholder="Password (6+ characters)" minlength="6" required><input type="password" id="signupConfirm" placeholder="Confirm password" minlength="6" required><button class="primary">CREATE RUNNER ACCOUNT</button><div class="muted">New public accounts are always created as Runner.</div><div id="signupMsg" class="error"></div></form>`;document.querySelector('#signupForm').onsubmit=async e=>{e.preventDefault();const msg=document.querySelector('#signupMsg'),btn=e.currentTarget.querySelector('.primary'),username=document.querySelector('#runnerName').value.trim(),email=document.querySelector('#signupEmail').value.trim(),password=document.querySelector('#signupPassword').value,confirm=document.querySelector('#signupConfirm').value;msg.className='error';msg.textContent='';if(username.length<2){msg.textContent='Runner name must be at least 2 characters.';return}if(password!==confirm){msg.textContent='Passwords do not match.';return}btn.disabled=true;btn.textContent='CREATING…';try{const {data,error}=await supabase.auth.signUp({email,password,options:{data:{username,role:'Runner'},emailRedirectTo:location.origin}});if(error)throw error;if(!data.user)throw Error('Account was not created.');const r=await fetch('/api/register-profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:data.user.id,email,username})});const raw=await r.text();let out={};try{out=raw?JSON.parse(raw):{}}catch{}if(!r.ok)throw Error(out.error||raw||`Runner profile could not be created (HTTP ${r.status}).`);msg.className='successText';msg.textContent=data.session?'ACCOUNT CREATED — signing you in…':'ACCOUNT CREATED — check your email to confirm it, then log in.';if(!data.session){btn.disabled=false;btn.textContent='CREATE RUNNER ACCOUNT'}}catch(err){msg.textContent=err.message||String(err);btn.disabled=false;btn.textContent='CREATE RUNNER ACCOUNT'}}}
  const forgot=()=>{panel.innerHTML=`<form id="forgotForm" class="formStack"><h2>RESET PASSWORD</h2><p class="muted">Enter your account email and we'll send a reset link.</p><input type="email" id="resetEmail" placeholder="Email" required><button class="primary">SEND RESET LINK</button><button type="button" class="ghost" id="backLogin">BACK TO LOGIN</button><div id="resetMsg" class="error"></div></form>`;document.querySelector('#backLogin').onclick=login;document.querySelector('#forgotForm').onsubmit=async e=>{e.preventDefault();const msg=document.querySelector('#resetMsg'),btn=e.currentTarget.querySelector('.primary');btn.disabled=true;btn.textContent='SENDING…';const {error}=await supabase.auth.resetPasswordForEmail(document.querySelector('#resetEmail').value.trim(),{redirectTo:location.origin});if(error){msg.textContent=error.message;btn.disabled=false;btn.textContent='SEND RESET LINK'}else{msg.className='successText';msg.textContent='RESET EMAIL SENT. Check your inbox.';btn.disabled=false;btn.textContent='SEND RESET LINK'}}}
  document.querySelector('#showLogin').onclick=login;document.querySelector('#showSignup').onclick=signup;login()
}

function countdownText(){if(!state.challenge)return 'NO ACTIVE CHALLENGE';const st=statusName(state.challenge.status);if(st!=='Active'||!state.challenge.ends_at)return st==='Reveal'?'TIMER NOT STARTED':'CHALLENGE NOT STARTED';const diff=new Date(state.challenge.ends_at).getTime()-Date.now();if(diff<=0)return 'CHALLENGE ENDED';const d=Math.floor(diff/86400000),h=Math.floor(diff%86400000/3600000),m=Math.floor(diff%3600000/60000),s=Math.floor(diff%60000/1000);return `${String(d).padStart(2,'0')} DAYS  ${String(h).padStart(2,'0')} HRS  ${String(m).padStart(2,'0')} MIN  ${String(s).padStart(2,'0')} SEC`}
function challengePage(){if(!state.challenge)return title('ACTIVE CHALLENGE','LIVE SUPABASE BACKEND')+`<div class="empty"><h2>NO SHARED CHALLENGE</h2></div>`;const n=state.games.length,uid=state.session.user.id,joined=state.members.some(m=>m.user_id===uid),best=new Map();for(const g of state.games){const vals=state.submissions.filter(s=>s.user_id===uid&&s.challenge_game_id===g.id).map(s=>s.time_ms);if(vals.length)best.set(g.id,Math.min(...vals))}const cards=state.games.map(g=>`<article class="gameCard ${best.has(g.id)?'done':''}"><div class="slot">GAME ${String(g.slot).padStart(2,'0')}</div><h3>${escapeHtml(g.game_name)}</h3><div class="platform">${escapeHtml(g.platform)}</div><p>${escapeHtml(g.goal_text||g.category_name||'Complete the listed category')}</p><strong>${best.has(g.id)?`PB ${fmtTime(best.get(g.id))}`:'NO TIME'}</strong>${statusName(state.challenge.status)==='Active'&&joined?`<button class="outline submitTime" data-gid="${g.id}">SUBMIT / IMPROVE</button>`:''}</article>`).join('');return title('ACTIVE CHALLENGE',`${escapeHtml(state.challenge.name)} • ${n} game${n===1?'':'s'} • ${n?`finish all ${n} to qualify`:'setup in progress'}`)+`<div class="countdownPanel"><span>TIME REMAINING</span><strong id="countdown">${countdownText()}</strong></div><div class="statusBar"><b>${statusName(state.challenge.status).toUpperCase()}</b><span>${best.size}/${n} COMPLETE</span>${statusName(state.challenge.status)==='Active'&&!joined?'<button class="primary small" id="join">JOIN CHALLENGE</button>':joined?'<span class="green">JOINED</span>':''}</div><div class="gameGrid">${cards}</div>`}
function overallPage(){if(!state.challenge)return title('OVERALL LEADERBOARD','No active challenge.');const n=state.games.length,rows=standings();const headers=state.games.map(g=>`<th title="${escapeHtml(g.game_name)}">G${g.slot}</th>`).join('');const body=rows.map((r,i)=>`<tr><td>${i+1}</td><td>${escapeHtml(r.username)}</td><td>${r.done}/${n}</td>${state.games.map(g=>`<td>${r.times.has(g.id)?fmtTime(r.times.get(g.id)):'—'}</td>`).join('')}<td class="${r.total!=null?'green':''}">${r.total!=null?fmtTime(r.total):'INCOMPLETE'}</td></tr>`).join('');return title('OVERALL LEADERBOARD',`${n}/${n} required to qualify • fastest combined PB total wins`)+`<div class="tableWrap leaderboardWide"><table><thead><tr><th>#</th><th>RUNNER</th><th>DONE</th>${headers}<th>TOTAL</th></tr></thead><tbody>${body}</tbody></table></div>`}
function gamesPage(){if(!state.games.length)return title('GAME LEADERBOARDS','No challenge games yet.')+`<div class="empty"><h2>NO GAMES</h2></div>`;return title('GAME LEADERBOARDS','Individual game standings do not determine the overall winner.')+`<select id="gameSelect">${state.games.map(g=>`<option value="${g.id}">Game ${g.slot}: ${escapeHtml(g.game_name)}</option>`).join('')}</select><div id="gameBoard"></div>`}
function renderGameBoard(gid){const g=state.games.find(x=>x.id===gid),pmap=new Map(state.profiles.map(p=>[p.id,p.username]));if(!g)return '';const ids=[...new Set(state.submissions.filter(s=>s.challenge_game_id===gid).map(s=>s.user_id))],rows=ids.map(uid=>({uid,name:pmap.get(uid)||'Runner',best:Math.min(...state.submissions.filter(s=>s.challenge_game_id===gid&&s.user_id===uid).map(s=>s.time_ms))})).sort((a,b)=>a.best-b.best);return `<h2 class="sectionHeading">${escapeHtml(g.game_name)}</h2><div class="tableWrap"><table><thead><tr><th>#</th><th>RUNNER</th><th>PB</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i+1}</td><td>${escapeHtml(r.name)}</td><td class="green">${fmtTime(r.best)}</td></tr>`).join('')}</tbody></table></div>`}
function monthlyCountdownText(){
  const x=state.monthly;if(!x)return 'NO ACTIVE MONTHLY GAME';
  if(x.timer_status==='stopped'){
    if(x.paused_remaining_ms!=null)return `PAUSED • ${formatDuration(Number(x.paused_remaining_ms))}`;
    return 'TIMER STOPPED';
  }
  if(x.timer_status==='ended')return 'MONTHLY CHALLENGE ENDED';
  if(!x.ends_at)return 'TIMER NOT STARTED';
  const diff=new Date(x.ends_at).getTime()-Date.now();
  if(diff<=0)return 'MONTHLY CHALLENGE ENDED';
  return formatDuration(diff);
}
function formatDuration(diff){const d=Math.floor(diff/86400000),h=Math.floor(diff%86400000/3600000),m=Math.floor(diff%3600000/60000),s=Math.floor(diff%60000/1000);return `${String(d).padStart(2,'0')} DAYS  ${String(h).padStart(2,'0')} HRS  ${String(m).padStart(2,'0')} MIN  ${String(s).padStart(2,'0')} SEC`}
function monthlyStandings(){const pmap=new Map(state.profiles.map(p=>[p.id,p.username])),ids=[...new Set(state.monthlySubmissions.map(s=>s.user_id))];return ids.map(uid=>{const rows=state.monthlySubmissions.filter(s=>s.user_id===uid);const best=Math.min(...rows.map(s=>Number(s.time_ms)));const bestRow=rows.filter(s=>Number(s.time_ms)===best).sort((a,b)=>new Date(a.submitted_at)-new Date(b.submitted_at))[0];return{uid,name:pmap.get(uid)||'Runner',best,submitted_at:bestRow?.submitted_at}}).sort((a,b)=>a.best-b.best||a.name.localeCompare(b.name))}
function monthlyPage(){
  const intro=title('GAME OF THE MONTH','Separate monthly challenge • its own timer and leaderboard • never affects the main Legends standings or Champions.');
  if(state.monthlyTableMissing)return intro+`<div class="infoBox"><h2>ONE-TIME SETUP REQUIRED</h2><p>Run <b>supabase/001_game_of_the_month.sql</b> in Supabase, then refresh.</p></div>`;
  if(!state.monthly)return intro+`<div class="empty"><h2>NO GAME OF THE MONTH SELECTED</h2><p>An Admin can choose one from Admin → Game of the Month.</p></div>`;
  if(state.monthlySetupMissing)return intro+`<div class="infoBox"><h2>ONE-TIME v0.1.8 SETUP REQUIRED</h2><p>Run <b>supabase/003_monthly_timer_leaderboard.sql</b> in Supabase once, then refresh. This adds the monthly timer and separate leaderboard.</p></div>`;
  const x=state.monthly,rows=monthlyStandings(),uid=state.session.user.id,userBest=rows.find(r=>r.uid===uid)?.best,open=x.timer_status==='running'&&x.ends_at&&new Date(x.ends_at).getTime()>Date.now();
  return intro+`<div class="countdownPanel monthlyCountdown"><span>MONTHLY TIME REMAINING</span><strong id="monthlyCountdown">${monthlyCountdownText()}</strong></div><div class="monthlyHero">${x.cover_url?`<img src="${escapeHtml(x.cover_url)}">`:''}<div><div class="eyebrow">${escapeHtml(x.month_key)}</div><h1>${escapeHtml(x.game_name)}</h1><b class="platform">${escapeHtml(x.platform)}</b><h3>${escapeHtml(x.goal_text||'Play it this month.')}</h3>${x.note?`<p>${escapeHtml(x.note)}</p>`:''}<div class="monthlyStatus"><b>${escapeHtml(String(x.timer_status||'stopped').toUpperCase())}</b>${userBest!=null?`<span class="green">YOUR PB ${fmtTime(userBest)}</span>`:''}</div>${open?'<button class="primary" id="monthlySubmit">SUBMIT / IMPROVE TIME</button>':''}</div></div><h2 class="sectionHeading">GAME OF THE MONTH LEADERBOARD</h2><div class="tableWrap"><table><thead><tr><th>#</th><th>RUNNER</th><th>PB</th><th>SUBMITTED</th></tr></thead><tbody>${rows.length?rows.map((r,i)=>`<tr><td>${i+1}</td><td>${escapeHtml(r.name)}</td><td class="green">${fmtTime(r.best)}</td><td>${r.submitted_at?new Date(r.submitted_at).toLocaleString():'—'}</td></tr>`).join(''):'<tr><td colspan="4">No monthly times submitted yet.</td></tr>'}</tbody></table></div>`
}
function championsPage(){return title('CHAMPIONS','Official winners from completed Legends challenges.')+`<div id="championsAll" class="pageLoading">LOADING CHAMPIONS…</div>`}
function profilePage(){return title('RUNNER PROFILE','Permanent runner record across Legends challenges.')+`<div id="profileFull" class="pageLoading">LOADING RUNNER PROFILE…</div>`}
function historyPage(){return title('CHALLENGE HISTORY','Completed and past Legends challenges remain here with their final results.')+`<div id="historyFull" class="pageLoading">LOADING CHALLENGE HISTORY…</div>`}
function creatorPage(){return title('CHALLENGE CREATOR','Create a NEW draft. Existing/current challenges are never resized or rewritten.')+`<form class="panel formStack" id="newChallenge"><input id="challengeName" value="Legends of Retro Challenge" placeholder="Challenge name" required><label>NUMBER OF GAMES — ANY NUMBER FROM 1 TO 100<input id="gameCount" type="number" min="1" max="100" value="10" required></label><div class="slotEditor" id="slots"></div><button class="primary">CREATE NEW DRAFT</button></form><div id="creatorMsg"></div>`}
function revealPage(){if(!state.challenge)return title('REVEAL CONTROL','No challenge exists.')+`<div class="empty"><h2>NO CHALLENGE</h2></div>`;const st=statusName(state.challenge.status);const cards=state.games.map(g=>`<article class="revealCard ${g.revealed?'revealed':''}"><div class="slot">GAME ${String(g.slot).padStart(2,'0')}</div><h3>${g.revealed||st==='Active'?escapeHtml(g.game_name):'???'}</h3><span>${g.revealed||st==='Active'?escapeHtml(g.platform||''):'LOCKED'}</span></article>`).join('');const unrevealed=state.games.filter(g=>!g.revealed),next=unrevealed[0];return title('REVEAL CONTROL',`Reveal is forced Game 01 → Game ${String(state.games.length).padStart(2,'0')}. The timer starts only after START CHALLENGE.`)+`<div class="revealGrid">${cards}</div><div class="revealActions">${st==='Draft'?'<button class="primary" id="lockReveal">BEGIN REVEAL</button>':''}${st==='Reveal'&&next?`<button class="primary" id="revealNext">REVEAL GAME ${String(next.slot).padStart(2,'0')}</button>`:''}${st==='Reveal'&&!next?'<button class="primary" id="startChallenge">START 30-DAY CHALLENGE</button>':''}${st==='Active'?'<div class="infoBox green">CHALLENGE ACTIVE</div>':''}</div><div id="revealMsg"></div>`}
function showMonthlySubmit(){
  if(!state.monthly||state.monthlySetupMissing)return;
  document.body.insertAdjacentHTML('beforeend',`<div class="modalBackdrop" id="monthlyModal"><div class="modal"><h2>${escapeHtml(state.monthly.game_name)}</h2><p>Submit a time for the separate Game of the Month leaderboard.</p><form id="monthlySubmitForm" class="formStack"><input id="monthlyTime" placeholder="M:SS.mmm or H:MM:SS.mmm" required><input id="monthlyProof" placeholder="Proof URL (optional)"><button class="primary">SUBMIT TIME</button><button type="button" class="ghost" id="monthlyCancel">CANCEL</button><div id="monthlySubmitMsg"></div></form></div></div>`);
  document.querySelector('#monthlyCancel').onclick=()=>document.querySelector('#monthlyModal')?.remove();
  document.querySelector('#monthlySubmitForm').onsubmit=async e=>{e.preventDefault();const msg=document.querySelector('#monthlySubmitMsg');try{const ms=parseTime(document.querySelector('#monthlyTime').value);const proof=document.querySelector('#monthlyProof').value.trim()||null;const {error}=await supabase.from('game_of_the_month_submissions').insert({game_of_the_month_id:state.monthly.id,user_id:state.session.user.id,time_ms:ms,proof_url:proof});if(error)throw error;document.querySelector('#monthlyModal')?.remove();await loadAll();render()}catch(err){msg.innerHTML=`<div class="errorBox">${escapeHtml(err.message||String(err))}</div>`}};
}
function adminPage(){return title('ADMIN CONTROLS','Manage runners and submissions. Full system/challenge controls are Admin-only.')+`<div class="adminTabs"><button class="outline adminTab" data-adminview="users">USERS</button><button class="outline adminTab" data-adminview="submissions">SUBMISSIONS</button><button class="outline adminTab" data-adminview="challenge">CHALLENGE</button><button class="outline adminTab" data-adminview="participants">PARTICIPANTS</button><button class="outline adminTab" data-adminview="activity">ACTIVITY LOG</button><button class="outline adminTab" data-adminview="system">SYSTEM</button><button class="outline adminTab" data-adminview="monthly">GAME OF THE MONTH</button></div><div id="adminView" class="panel"></div>`}
function wirePage(){if(state.tab==='challenge'){const join=document.querySelector('#join');if(join)join.onclick=async()=>{const {error}=await supabase.from('challenge_members').upsert({challenge_id:state.challenge.id,user_id:state.session.user.id,joined_at:new Date().toISOString()},{onConflict:'challenge_id,user_id'});if(error)return alert(error.message);await loadAll();render()};document.querySelectorAll('.submitTime').forEach(b=>b.onclick=()=>showSubmit(Number(b.dataset.gid)));if(document.querySelector('#countdown'))countdownHandle=setInterval(()=>{const el=document.querySelector('#countdown');if(el)el.textContent=countdownText()},1000)}if(state.tab==='games'){const s=document.querySelector('#gameSelect'),board=document.querySelector('#gameBoard');const update=()=>board.innerHTML=renderGameBoard(Number(s.value));s.onchange=update;update()}if(state.tab==='monthly'){const b=document.querySelector('#monthlySubmit');if(b)b.onclick=showMonthlySubmit;if(document.querySelector('#monthlyCountdown'))countdownHandle=setInterval(()=>{const el=document.querySelector('#monthlyCountdown');if(el)el.textContent=monthlyCountdownText()},1000)}if(state.tab==='champions')loadChampionsAll();if(state.tab==='profile')loadProfileFull();if(state.tab==='history')loadHistory();if(state.tab==='creator')wireCreator();if(state.tab==='reveal')wireReveal();if(state.tab==='admin')wireAdmin()}
function showSubmit(gid){const g=state.games.find(x=>x.id===gid);if(!g)return;document.body.insertAdjacentHTML('beforeend',`<div class="modalBackdrop" id="modal"><div class="modal"><h2>SUBMIT TIME</h2><h3>${escapeHtml(g.game_name)}</h3><form class="formStack" id="submitForm"><input id="timeVal" placeholder="M:SS.mmm or H:MM:SS.mmm" required><input id="proofVal" placeholder="Proof link (optional)"><button class="primary">SUBMIT TIME</button><button type="button" class="ghost" id="cancel">CANCEL</button><div class="error" id="submitMsg"></div></form></div></div>`);const modal=document.querySelector('#modal');document.querySelector('#cancel').onclick=()=>modal.remove();modal.onclick=e=>{if(e.target===modal)modal.remove()};document.querySelector('#submitForm').onsubmit=async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('.primary');btn.disabled=true;btn.textContent='SUBMITTING…';try{const ms=parseTime(document.querySelector('#timeVal').value);const {error}=await supabase.from('submissions').insert({challenge_id:state.challenge.id,challenge_game_id:g.id,user_id:state.session.user.id,time_ms:ms,proof_url:document.querySelector('#proofVal').value.trim()||null,submitted_at:new Date().toISOString()});if(error)throw error;modal.remove();await loadAll();render()}catch(err){document.querySelector('#submitMsg').textContent=err.message||String(err);btn.disabled=false;btn.textContent='SUBMIT TIME'}}}
async function loadChampionsAll(){const box=document.querySelector('#championsAll');const [cp,p,c]=await Promise.all([supabase.from('champions').select('challenge_id,user_id,total_time_ms,awarded_at').order('challenge_id',{ascending:false}),supabase.from('profiles').select('id,username'),supabase.from('challenges').select('id,name')]);const err=[cp.error,p.error,c.error].find(Boolean);if(err){box.className='errorBox';box.textContent=err.message;return}const pm=new Map((p.data||[]).map(x=>[x.id,x.username])),cm=new Map((c.data||[]).map(x=>[x.id,x.name])),rows=cp.data||[];box.className='champGrid';box.innerHTML=rows.length?rows.map(r=>`<article class="champCard"><div class="trophy">🏆</div><div class="muted">${escapeHtml(cm.get(r.challenge_id)||`Challenge ${r.challenge_id}`)}</div><h2>${escapeHtml(pm.get(r.user_id)||'Runner')}</h2><b>CHAMPION</b><strong>${fmtTime(r.total_time_ms)}</strong></article>`).join(''):`<div class="champEmpty"><div>🏆</div><h2>NO CHAMPIONS YET</h2></div>`}
async function loadProfileFull(){const box=document.querySelector('#profileFull'),uid=state.session.user.id;const [chs,gms,mem,subs,cps]=await Promise.all([supabase.from('challenges').select('id,name,status,created_at,started_at,ends_at,completed_at').order('id',{ascending:false}),supabase.from('challenge_games').select('id,challenge_id,slot'),supabase.from('challenge_members').select('challenge_id,user_id,joined_at').eq('user_id',uid),supabase.from('submissions').select('challenge_id,challenge_game_id,user_id,time_ms,submitted_at').eq('user_id',uid),supabase.from('champions').select('challenge_id,user_id,total_time_ms').eq('user_id',uid)]);const err=[chs.error,gms.error,mem.error,subs.error,cps.error].find(Boolean);if(err){box.className='errorBox';box.textContent=err.message;return}const memberships=mem.data||[],submissions=subs.data||[],champions=cps.data||[],games=gms.data||[];const joined=memberships.length,submitted=submissions.length,champCount=champions.length;let finishes=0;const results=[];for(const ch of chs.data||[]){if(!memberships.some(m=>m.challenge_id===ch.id)&&!submissions.some(s=>s.challenge_id===ch.id))continue;const cg=games.filter(g=>g.challenge_id===ch.id),done=new Set(submissions.filter(s=>s.challenge_id===ch.id).map(s=>s.challenge_game_id)).size;if(cg.length&&done===cg.length)finishes++;results.push(`<tr><td>${escapeHtml(ch.name)}</td><td>${done}/${cg.length}</td><td>${champions.some(c=>c.challenge_id===ch.id)?'CHAMPION':statusName(ch.status).toUpperCase()}</td></tr>`)}box.className='';box.innerHTML=`<div class="profileHero"><div><span class="eyebrow">${escapeHtml(state.profile.role).toUpperCase()}</span><h1>${escapeHtml(state.profile.username)}</h1><button class="outline" id="editRunner">EDIT PROFILE / RUNNER NAME</button></div><div class="stat"><strong>${joined}</strong><span>CHALLENGES JOINED</span></div><div class="stat"><strong>${finishes}</strong><span>FINISHES</span></div><div class="stat"><strong>${champCount}</strong><span>CHAMPIONSHIPS</span></div><div class="stat"><strong>${submitted}</strong><span>TIMES SUBMITTED</span></div></div><h2 class="sectionHeading">CHALLENGE RESULTS</h2><div class="tableWrap"><table><thead><tr><th>CHALLENGE</th><th>RESULT</th><th>STATUS</th></tr></thead><tbody>${results.join('')||'<tr><td colspan="3">No challenge results yet.</td></tr>'}</tbody></table></div>`;document.querySelector('#editRunner').onclick=async()=>{const name=prompt('Runner name',state.profile.username);if(!name||!name.trim())return;const {error}=await supabase.from('profiles').update({username:name.trim()}).eq('id',uid);if(error)return alert(error.message);state.profile.username=name.trim();await loadAll();render()}}
async function loadHistory(){const box=document.querySelector('#historyFull');const [chs,gms,mem,cps]=await Promise.all([supabase.from('challenges').select('id,name,status,created_at,started_at,ends_at,completed_at').order('id',{ascending:false}),supabase.from('challenge_games').select('id,challenge_id'),supabase.from('challenge_members').select('challenge_id,user_id'),supabase.from('champions').select('challenge_id,user_id,total_time_ms')]);const err=[chs.error,gms.error,mem.error,cps.error].find(Boolean);if(err){box.className='errorBox';box.textContent=err.message;return}const rows=(chs.data||[]).filter(c=>statusName(c.status)==='Complete').map(c=>`<tr><td>${escapeHtml(c.name)}</td><td>${gms.data.filter(g=>g.challenge_id===c.id).length}</td><td>${mem.data.filter(m=>m.challenge_id===c.id).length}</td><td>${cps.data.filter(x=>x.challenge_id===c.id).length}</td><td>${c.completed_at?new Date(c.completed_at).toLocaleDateString():c.ends_at?new Date(c.ends_at).toLocaleDateString():'—'}</td></tr>`);box.className='tableWrap';box.innerHTML=`<table><thead><tr><th>CHALLENGE</th><th>GAMES</th><th>RUNNERS</th><th>CHAMPIONS</th><th>ENDED</th></tr></thead><tbody>${rows.join('')||'<tr><td colspan="5">No completed challenges yet.</td></tr>'}</tbody></table>`}
function wireCreator(){const slots=document.querySelector('#slots'),count=document.querySelector('#gameCount'),msg=document.querySelector('#creatorMsg');const draw=()=>{const n=Math.max(1,Math.min(100,Number(count.value)||1));count.value=n;slots.innerHTML=Array.from({length:n},(_,i)=>`<div class="slotRow"><b>${i+1}</b><input class="slotName" placeholder="Game name" required><select class="slotPlatform"><option>NES</option><option>SNES</option><option>Genesis</option></select><input class="slotGoal" value="Any%" placeholder="Category / goal"></div>`).join('')};count.onchange=draw;draw();document.querySelector('#newChallenge').onsubmit=async e=>{e.preventDefault();msg.innerHTML='';const blocking=state.challenges.find(c=>['Active','Reveal'].includes(statusName(c.status)));if(blocking){msg.innerHTML=`<div class="errorBox">Finish the current ${statusName(blocking.status)} challenge before creating another shared challenge.</div>`;return}const names=[...document.querySelectorAll('.slotName')],plats=[...document.querySelectorAll('.slotPlatform')],goals=[...document.querySelectorAll('.slotGoal')],n=names.length;const {data:ch,error}=await supabase.from('challenges').insert({name:document.querySelector('#challengeName').value.trim(),status:'Draft',created_by:state.session.user.id}).select('id').single();if(error){msg.innerHTML=`<div class="errorBox">${escapeHtml(error.message)}</div>`;return}const rows=names.map((x,i)=>({challenge_id:ch.id,slot:i+1,game_name:x.value.trim(),platform:plats[i].value,goal_text:goals[i].value.trim()||'Complete the game / category goal',revealed:false}));const {error:ge}=await supabase.from('challenge_games').insert(rows);if(ge){await supabase.from('challenges').delete().eq('id',ch.id);msg.innerHTML=`<div class="errorBox">${escapeHtml(ge.message)}</div>`;return}msg.innerHTML=`<div class="infoBox">Created a ${n}-game NEW draft. Existing challenges were not changed.</div>`;await loadAll();render()}}
function wireReveal(){const msg=document.querySelector('#revealMsg');const lock=document.querySelector('#lockReveal');if(lock)lock.onclick=async()=>{const {error}=await supabase.from('challenges').update({status:'Reveal'}).eq('id',state.challenge.id);if(error)return msg.innerHTML=`<div class="errorBox">${escapeHtml(error.message)}</div>`;await loadAll();render()};const next=document.querySelector('#revealNext');if(next)next.onclick=async()=>{const g=state.games.filter(x=>!x.revealed).sort((a,b)=>a.slot-b.slot)[0];if(!g)return;const {error}=await supabase.from('challenge_games').update({revealed:true}).eq('id',g.id);if(error)return msg.innerHTML=`<div class="errorBox">${escapeHtml(error.message)}</div>`;await loadAll();render()};const start=document.querySelector('#startChallenge');if(start)start.onclick=async()=>{const now=new Date(),end=new Date(now.getTime()+30*86400000);const {error}=await supabase.from('challenges').update({status:'Active',started_at:now.toISOString(),ends_at:end.toISOString(),revealed_at:now.toISOString()}).eq('id',state.challenge.id);if(error)return msg.innerHTML=`<div class="errorBox">${escapeHtml(error.message)}</div>`;await loadAll();state.tab='challenge';render()}}
function selectedAdminRow(selector){return document.querySelector(`${selector} tr.selected`)?.dataset.id||null}
function wireSelectableRows(selector){document.querySelectorAll(`${selector} tbody tr[data-id]`).forEach(tr=>tr.onclick=()=>{document.querySelectorAll(`${selector} tbody tr`).forEach(x=>x.classList.remove('selected'));tr.classList.add('selected')})}
async function adminApi(path,body){const {data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)throw Error('Your login session expired. Refresh and sign in again.');const res=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},body:JSON.stringify(body)});const out=await res.json().catch(()=>({}));if(!res.ok)throw Error(out.error||out.message||`Admin request failed (${res.status})`);return out}
function dlText(name,text,type='text/plain'){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function audit(action,details=''){try{await adminApi('/api/admin-data',{action:'audit',details:{action,details}})}catch(e){console.warn('Audit log write failed',e)}}
function userButtons(){return `<div class="adminActions"><button class="primary" id="addAccount">+ ADD ACCOUNT</button><button class="outline" id="toggleAccount">ENABLE / DISABLE</button><button class="outline" id="resetAccount">RESET PASSWORD</button><button class="outline" id="roleAccount">CHANGE ROLE</button><button class="outline" id="editAccount">EDIT ACCOUNT</button><button class="danger" id="removeAccount">REMOVE ACCOUNT</button></div><div id="adminMsg"></div>`}
async function wireAdmin(){const view=document.querySelector('#adminView'),tabs=[...document.querySelectorAll('.adminTab')];let current='users';const setMsg=(html)=>{const x=document.querySelector('#adminMsg');if(x)x.innerHTML=html};const errBox=e=>`<div class="errorBox">${escapeHtml(e.message||String(e))}</div>`;async function show(kind){current=kind;tabs.forEach(b=>b.classList.toggle('activeAdmin',b.dataset.adminview===kind));view.innerHTML='<div class="loadingInline">Loading…</div>';try{
if(kind==='users'){
 let users=[];let secured=true;try{const out=await adminApi('/api/admin-user',{action:'list'});users=out.users||[]}catch(e){secured=false;const {data,error}=await supabase.from('profiles').select('id,username,role,disabled').order('username');if(error)throw e;users=data||[]}
 view.innerHTML=`<h2>USERS</h2><div class="tableWrap"><table id="adminUsers"><thead><tr><th>ID</th><th>USERNAME</th><th>EMAIL</th><th>ROLE</th><th>DISABLED</th></tr></thead><tbody>${users.map(u=>`<tr data-id="${u.id}"><td class="idCell">${escapeHtml(String(u.id).slice(0,8))}</td><td>${escapeHtml(u.username||'')}</td><td>${escapeHtml(u.email||'')}</td><td>${escapeHtml(u.role||'Runner')}</td><td>${u.disabled?'YES':'NO'}</td></tr>`).join('')}</tbody></table></div>${userButtons()}${secured?'':'<div class="warnBox">Account-security API is not configured yet. Add the Vercel SUPABASE_SERVICE_ROLE_KEY environment variable to enable these buttons.</div>'}`;wireSelectableRows('#adminUsers');
 const need=()=>{const id=selectedAdminRow('#adminUsers');if(!id)throw Error('Select a user first.');return id};
 document.querySelector('#addAccount').onclick=async()=>{const username=prompt('Username:');if(!username)return;const email=prompt('Email:');if(!email)return;const password=prompt('Temporary password (6+ characters):');if(!password)return;try{await adminApi('/api/admin-user',{action:'create',username:username.trim(),email:email.trim(),password});await show('users')}catch(e){setMsg(errBox(e))}};
 document.querySelector('#toggleAccount').onclick=async()=>{try{const id=need();await adminApi('/api/admin-user',{action:'toggleDisabled',userId:id});await show('users')}catch(e){setMsg(errBox(e))}};
 document.querySelector('#resetAccount').onclick=async()=>{try{const id=need(),p1=prompt('New password (6+ characters):');if(!p1)return;const p2=prompt('Confirm new password:');if(p1!==p2)throw Error('Passwords do not match.');await adminApi('/api/admin-user',{action:'resetPassword',userId:id,password:p1});alert('Password reset.')}catch(e){setMsg(errBox(e))}};
 document.querySelector('#roleAccount').onclick=async()=>{try{const id=need(),role=prompt('New role: Runner, Moderator, or Admin','Runner');if(!role)return;await adminApi('/api/admin-user',{action:'changeRole',userId:id,role});await show('users')}catch(e){setMsg(errBox(e))}};
 document.querySelector('#editAccount').onclick=async()=>{try{const id=need(),row=users.find(x=>x.id===id);const username=prompt('Username:',row?.username||'');if(!username)return;const email=prompt('Email:',row?.email||'');if(email===null)return;await adminApi('/api/admin-user',{action:'edit',userId:id,username:username.trim(),email:email.trim()});await show('users')}catch(e){setMsg(errBox(e))}};
 document.querySelector('#removeAccount').onclick=async()=>{try{const id=need(),row=users.find(x=>x.id===id);if(id===state.session.user.id)throw Error('You cannot remove your own logged-in account.');if(!confirm(`Permanently remove ${row?.username||'this runner'}? Their submissions and memberships will also be removed.`))return;await adminApi('/api/admin-user',{action:'delete',userId:id});await loadAll();await show('users')}catch(e){setMsg(errBox(e))}};
}
else if(kind==='submissions'){
 const notes={};try{const {data}=await supabase.from('submission_notes').select('submission_id,note');(data||[]).forEach(n=>notes[n.submission_id]=n.note)}catch{}
 view.innerHTML=`<h2>SUBMISSIONS</h2><div class="tableWrap"><table id="adminSubs"><thead><tr><th>ID</th><th>RUNNER</th><th>GAME</th><th>TIME</th><th>DATE</th><th>NOTE</th></tr></thead><tbody>${state.submissions.slice().sort((a,b)=>Number(b.id)-Number(a.id)).map(s=>`<tr data-id="${s.id}"><td>${s.id}</td><td>${escapeHtml(state.profiles.find(p=>p.id===s.user_id)?.username||'Runner')}</td><td>${escapeHtml(state.games.find(g=>g.id===s.challenge_game_id)?.game_name||'Game')}</td><td>${fmtTime(s.time_ms)}</td><td>${s.submitted_at?new Date(s.submitted_at).toLocaleString():'—'}</td><td>${escapeHtml(notes[s.id]||'—')}</td></tr>`).join('')}</tbody></table></div><div id="selectedNote" class="noteBar">NOTE: Select a submission to view its note.</div><div class="adminActions"><button class="outline" id="correctSub">CORRECT TIME</button><button class="danger" id="deleteSub">DELETE BAD SUBMISSION</button><button class="outline" id="noteSub">ADD / EDIT NOTE</button></div><div id="adminMsg"></div>`;wireSelectableRows('#adminSubs');document.querySelectorAll('#adminSubs tbody tr').forEach(tr=>tr.addEventListener('click',()=>document.querySelector('#selectedNote').textContent='NOTE: '+(notes[tr.dataset.id]||'— No note —')));const need=()=>{const id=selectedAdminRow('#adminSubs');if(!id)throw Error('Select a submission first.');return Number(id)};
 document.querySelector('#correctSub').onclick=async()=>{try{const id=need(),v=prompt('Correct time (MM:SS.mmm or HH:MM:SS.mmm):');if(!v)return;const ms=parseTime(v);await adminApi('/api/admin-data',{action:'correctSubmission',submissionId:id,timeMs:ms});await loadAll();await show('submissions')}catch(e){setMsg(errBox(e))}};
 document.querySelector('#deleteSub').onclick=async()=>{try{const id=need();if(!confirm('Delete this submission permanently?'))return;await adminApi('/api/admin-data',{action:'deleteSubmission',submissionId:id});await loadAll();await show('submissions')}catch(e){setMsg(errBox(e))}};
 document.querySelector('#noteSub').onclick=async()=>{try{const id=need(),old=notes[id]||'',note=prompt('Admin/Moderator note:',old);if(note===null)return;await adminApi('/api/admin-data',{action:'noteSubmission',submissionId:id,note:note.trim()});await show('submissions')}catch(e){setMsg(errBox(e))}};
}
else if(kind==='challenge'){
 const ch=state.challenge;view.innerHTML=`<h2>${escapeHtml(ch?.name||'NO CHALLENGE')}</h2><p>Status: <b>${escapeHtml(statusName(ch?.status))}</b> &nbsp;&nbsp; End: <b>${ch?.ends_at?new Date(ch.ends_at).toLocaleString():'Not started'}</b></p><div class="adminActions"><button class="outline extend" data-days="1">+ 1 DAY</button><button class="outline extend" data-days="3">+ 3 DAYS</button><button class="outline extend" data-days="7">+ 7 DAYS</button><button class="danger" id="endNow">END CHALLENGE NOW</button></div><div class="adminActions"><button class="outline" id="editChallenge">EDIT CHALLENGE SETTINGS</button><button class="outline" id="reopenChallenge">REOPEN CHALLENGE</button><button class="outline" id="recalcChallenge">RECALCULATE STANDINGS</button></div><h3 class="sectionHeading">EDIT / REPLACE ACTIVE CHALLENGE GAMES</h3><p class="muted">Change one game without rebuilding the challenge. If that slot already has submissions, you choose whether to keep or clear them.</p><div class="tableWrap"><table id="challengeGameAdmin"><thead><tr><th>SLOT</th><th>GAME</th><th>SYSTEM</th><th>GOAL</th><th>SUBMISSIONS</th><th>ACTION</th></tr></thead><tbody>${state.games.map(g=>{const count=state.submissions.filter(s=>s.challenge_game_id===g.id).length;return `<tr><td>G${g.slot}</td><td>${escapeHtml(g.game_name)}</td><td>${escapeHtml(g.platform||'')}</td><td>${escapeHtml(g.goal_text||g.category_name||'')}</td><td>${count}</td><td><button class="outline editGame" data-gid="${g.id}">EDIT / REPLACE</button></td></tr>`}).join('')}</tbody></table></div><div id="adminMsg"></div>`;if(!ch)return;
 document.querySelectorAll('.extend').forEach(b=>b.onclick=async()=>{try{await adminApi('/api/admin-data',{action:'extendChallenge',challengeId:ch.id,days:Number(b.dataset.days)});await loadAll();await show('challenge')}catch(e){setMsg(errBox(e))}});
 document.querySelector('#endNow').onclick=async()=>{try{if(!confirm('End and finalize this challenge now?'))return;await adminApi('/api/admin-data',{action:'endChallenge',challengeId:ch.id});await loadAll();await show('challenge')}catch(e){setMsg(errBox(e))}};
 document.querySelector('#editChallenge').onclick=async()=>{try{const name=prompt('Challenge name:',ch.name);if(!name)return;const current=ch.ends_at?new Date(ch.ends_at).toISOString().slice(0,16):'',end=prompt('End date/time (YYYY-MM-DDTHH:MM). Leave blank if not started:',current);if(end===null)return;await adminApi('/api/admin-data',{action:'editChallenge',challengeId:ch.id,name:name.trim(),endsAt:end.trim()?new Date(end).toISOString():null});await loadAll();await show('challenge')}catch(e){setMsg(errBox(e))}};
 document.querySelector('#reopenChallenge').onclick=async()=>{try{if(!confirm('Reopen this challenge as ACTIVE?'))return;await adminApi('/api/admin-data',{action:'reopenChallenge',challengeId:ch.id});await loadAll();await show('challenge')}catch(e){setMsg(errBox(e))}};
 document.querySelector('#recalcChallenge').onclick=async()=>{try{await adminApi('/api/admin-data',{action:'recalculate',challengeId:ch.id});await loadAll();alert('Standings and Champion records recalculated.')}catch(e){setMsg(errBox(e))}};
 document.querySelectorAll('.editGame').forEach(btn=>btn.onclick=async()=>{try{const g=state.games.find(x=>x.id===Number(btn.dataset.gid));if(!g)throw Error('Game not found.');const gameName=prompt(`Game ${g.slot} name:`,g.game_name);if(gameName===null||!gameName.trim())return;const platform=prompt('System (NES, SNES, Genesis):',g.platform||'NES');if(platform===null||!platform.trim())return;const goal=prompt('Category / goal:',g.goal_text||g.category_name||'Any%');if(goal===null)return;const count=state.submissions.filter(s=>s.challenge_game_id===g.id).length;let submissionMode='keep';if(count){const choice=prompt(`${count} submission(s) already exist for this slot. Type KEEP to preserve them, CLEAR to delete them, or CANCEL to abort.`,'KEEP');if(choice===null||choice.trim().toUpperCase()==='CANCEL')return;const c=choice.trim().toUpperCase();if(!['KEEP','CLEAR'].includes(c))throw Error('Type KEEP, CLEAR, or CANCEL.');submissionMode=c.toLowerCase()}if(!confirm(`Replace Game ${g.slot} with ${gameName.trim()} (${platform.trim()})?${count?` Existing submissions will be ${submissionMode.toUpperCase()}.`:''}`))return;await adminApi('/api/admin-data',{action:'editChallengeGame',challengeId:ch.id,gameId:g.id,gameName:gameName.trim(),platform:platform.trim(),goalText:goal.trim()||null,submissionMode});await loadAll();await show('challenge')}catch(e){setMsg(errBox(e))}});
}
else if(kind==='participants'){
 view.innerHTML=`<h2>PARTICIPANTS</h2><div class="tableWrap"><table id="adminMembers"><thead><tr><th>ID</th><th>RUNNER</th><th>ROLE</th><th>JOINED</th></tr></thead><tbody>${state.members.map(m=>{const p=state.profiles.find(x=>x.id===m.user_id);return `<tr data-id="${m.user_id}"><td class="idCell">${String(m.user_id).slice(0,8)}</td><td>${escapeHtml(p?.username||'Runner')}</td><td>${escapeHtml(p?.role||'Runner')}</td><td>${m.joined_at?new Date(m.joined_at).toLocaleString():'—'}</td></tr>`}).join('')}</tbody></table></div><div class="adminActions"><button class="primary" id="addParticipant">+ ADD PARTICIPANT</button><button class="danger" id="removeParticipant">REMOVE PARTICIPANT</button></div><div id="adminMsg"></div>`;wireSelectableRows('#adminMembers');
 document.querySelector('#addParticipant').onclick=async()=>{try{const username=prompt('Runner username:');if(!username)return;await adminApi('/api/admin-data',{action:'addParticipant',challengeId:state.challenge.id,username:username.trim()});await loadAll();await show('participants')}catch(e){setMsg(errBox(e))}};
 document.querySelector('#removeParticipant').onclick=async()=>{try{const id=selectedAdminRow('#adminMembers');if(!id)throw Error('Select a participant first.');if(!confirm('Remove this runner from the challenge? Their current challenge submissions will be deleted.'))return;await adminApi('/api/admin-data',{action:'removeParticipant',challengeId:state.challenge.id,userId:id});await loadAll();await show('participants')}catch(e){setMsg(errBox(e))}};
}
else if(kind==='activity'){
 const {data,error}=await supabase.from('audit_log').select('*').order('created_at',{ascending:false}).limit(500);if(error)throw error;const rows=data||[];view.innerHTML=`<h2>ACTIVITY LOG</h2><div class="tableWrap"><table><thead><tr><th>DATE</th><th>USER</th><th>ACTION</th><th>DETAILS</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.created_at?new Date(r.created_at).toLocaleString():'—'}</td><td>${escapeHtml(r.username||r.user_name||r.actor_name||state.profiles.find(p=>p.id===r.user_id)?.username||'SYSTEM')}</td><td>${escapeHtml(r.action||'')}</td><td>${escapeHtml(r.details||'')}</td></tr>`).join('')||'<tr><td colspan="4">No activity recorded yet.</td></tr>'}</tbody></table></div>`;
}
else if(kind==='system'){
 view.innerHTML=`<h2>ONLINE SYSTEM / BROWSER EXPORTS</h2><p>Legends of Retro is connected to the shared Supabase backend. There is no local SQLite database inside the browser, so the safe web equivalents are downloadable exports.</p><div class="systemStatus"><b>Supabase:</b> connected &nbsp; <b>Auth refresh:</b> enabled &nbsp; <b>Web build:</b> v0.1.3</div><div class="adminActions"><button class="primary" id="backupJson">DOWNLOAD ONLINE BACKUP JSON</button><button class="outline" id="exportCsv">EXPORT RESULTS CSV</button></div><p class="muted">Restore remains a desktop-only local-cache feature; the website will not overwrite the live online database from an uploaded backup.</p>`;
 document.querySelector('#backupJson').onclick=async()=>{const backup={exported_at:new Date().toISOString(),challenge:state.challenge,games:state.games,submissions:state.submissions,members:state.members,profiles:state.profiles,champions:state.champions};dlText(`legends_online_backup_${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(backup,null,2),'application/json')};
 document.querySelector('#exportCsv').onclick=()=>{const lines=[['Runner','Game','Platform','Best Time']];for(const r of standings())for(const g of state.games)if(r.times.has(g.id))lines.push([r.username,g.game_name,g.platform||'',fmtTime(r.times.get(g.id))]);const csv=lines.map(row=>row.map(x=>`"${String(x).replaceAll('"','""')}"`).join(',')).join('\r\n');dlText('legends_results.csv',csv,'text/csv')};
}
else if(kind==='monthly'){
 const x=state.monthly;const currentEnd=x?.ends_at?new Date(new Date(x.ends_at).getTime()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16):'';
 view.innerHTML=`<form class="formStack" id="monthlyForm"><h2>GAME OF THE MONTH</h2><p class="muted">Separate timer and leaderboard. Nothing here changes the main Challenge standings or Champions.</p>${state.monthlySetupMissing?'<div class="warnBox">Run supabase/003_monthly_timer_leaderboard.sql once before using timer controls or monthly submissions.</div>':''}<label>Month</label><input id="monthKey" type="month" value="${x?.month_key||new Date().toISOString().slice(0,7)}" required><label>Game</label><input id="monthGame" placeholder="Game name" value="${escapeHtml(x?.game_name||'')}" required><label>System</label><select id="monthPlatform"><option>NES</option><option>SNES</option><option>Genesis</option></select><label>Category / goal</label><input id="monthGoal" placeholder="Suggested category / goal" value="${escapeHtml(x?.goal_text||'')}"><label>Note</label><textarea id="monthNote" placeholder="Monthly note">${escapeHtml(x?.note||'')}</textarea><label>End date / time</label><input id="monthEnd" type="datetime-local" value="${currentEnd}"><button class="primary">SAVE / CHANGE GAME OF THE MONTH</button></form><div class="monthlyAdminTimer"><h3>TIMER CONTROL</h3><div class="countdownPanel"><span>CURRENT TIMER</span><strong>${x?monthlyCountdownText():'NO MONTHLY GAME'}</strong></div><div class="adminActions"><button class="primary" id="monthStart" ${!x||state.monthlySetupMissing?'disabled':''}>START / RESUME</button><button class="outline" id="monthStop" ${!x||state.monthlySetupMissing?'disabled':''}>STOP / PAUSE</button><button class="outline" id="monthReset" ${!x||state.monthlySetupMissing?'disabled':''}>RESET TO 30 DAYS</button><button class="danger" id="monthEndNow" ${!x||state.monthlySetupMissing?'disabled':''}>END NOW</button></div></div><div id="monthlyMsg"></div>`;
 document.querySelector('#monthPlatform').value=x?.platform||'NES';const msg=document.querySelector('#monthlyMsg');
 document.querySelector('#monthlyForm').onsubmit=async e=>{e.preventDefault();try{if(state.monthlyTableMissing)throw Error('Run supabase/001_game_of_the_month.sql once first.');await supabase.from('game_of_the_month').update({active:false}).eq('active',true);const endVal=document.querySelector('#monthEnd').value;const row={month_key:document.querySelector('#monthKey').value,game_name:document.querySelector('#monthGame').value.trim(),platform:document.querySelector('#monthPlatform').value,goal_text:document.querySelector('#monthGoal').value.trim()||null,note:document.querySelector('#monthNote').value.trim()||null,active:true,created_by:state.session.user.id};if(!state.monthlySetupMissing){row.ends_at=endVal?new Date(endVal).toISOString():null;if(!x)row.timer_status='stopped'}const {error}=await supabase.from('game_of_the_month').upsert(row,{onConflict:'month_key'});if(error)throw error;await loadAll();msg.innerHTML='<div class="infoBox">Game of the Month saved. Its leaderboard remains separate from the active challenge.</div>';await show('monthly')}catch(e){msg.innerHTML=errBox(e)}};
 const updateTimer=async patch=>{const {error}=await supabase.from('game_of_the_month').update(patch).eq('id',state.monthly.id);if(error)throw error;await loadAll();await show('monthly')};
 const start=document.querySelector('#monthStart');if(start)start.onclick=async()=>{try{const now=Date.now(),remaining=Number(state.monthly.paused_remaining_ms);let end;if(remaining>0)end=new Date(now+remaining);else if(state.monthly.ends_at&&new Date(state.monthly.ends_at).getTime()>now)end=new Date(state.monthly.ends_at);else end=new Date(now+30*86400000);await updateTimer({timer_status:'running',starts_at:state.monthly.starts_at||new Date(now).toISOString(),ends_at:end.toISOString(),paused_remaining_ms:null})}catch(e){msg.innerHTML=errBox(e)}};
 const stop=document.querySelector('#monthStop');if(stop)stop.onclick=async()=>{try{const remaining=Math.max(0,(state.monthly.ends_at?new Date(state.monthly.ends_at).getTime():Date.now())-Date.now());await updateTimer({timer_status:'stopped',paused_remaining_ms:remaining})}catch(e){msg.innerHTML=errBox(e)}};
 const reset=document.querySelector('#monthReset');if(reset)reset.onclick=async()=>{try{if(!confirm('Reset the Game of the Month timer to a fresh 30 days starting now? Existing monthly submissions will be kept.'))return;const now=Date.now();await updateTimer({timer_status:'running',starts_at:new Date(now).toISOString(),ends_at:new Date(now+30*86400000).toISOString(),paused_remaining_ms:null})}catch(e){msg.innerHTML=errBox(e)}};
 const endNow=document.querySelector('#monthEndNow');if(endNow)endNow.onclick=async()=>{try{if(!confirm('End the Game of the Month now? The monthly leaderboard will remain visible.'))return;await updateTimer({timer_status:'ended',ends_at:new Date().toISOString(),paused_remaining_ms:0})}catch(e){msg.innerHTML=errBox(e)}};
}
}catch(e){view.innerHTML=errBox(e)}}tabs.forEach(b=>b.onclick=()=>show(b.dataset.adminview));await show('users')}

boot().catch(err=>{console.error(err);app.innerHTML=`<div class="loginPage"><div class="errorBox"><h2>LEGENDS WEB ERROR</h2><p>${escapeHtml(err.message||String(err))}</p></div></div>`})
