-- Legends of Retro Web v0.1
-- Adds ONLY the separate Game of the Month feature.
-- It does not alter challenges, challenge_games, submissions, champions, or existing results.

create table if not exists public.game_of_the_month (
  id bigint generated by default as identity primary key,
  month_key text not null unique,
  game_name text not null,
  platform text not null,
  goal_text text,
  note text,
  cover_url text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id)
);

alter table public.game_of_the_month enable row level security;
grant select, insert, update, delete on table public.game_of_the_month to authenticated;

drop policy if exists "GOTM authenticated read" on public.game_of_the_month;
create policy "GOTM authenticated read" on public.game_of_the_month for select to authenticated using (true);

drop policy if exists "GOTM admin insert" on public.game_of_the_month;
create policy "GOTM admin insert" on public.game_of_the_month for insert to authenticated
with check (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role='Admin'));

drop policy if exists "GOTM admin update" on public.game_of_the_month;
create policy "GOTM admin update" on public.game_of_the_month for update to authenticated
using (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role='Admin'))
with check (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role='Admin'));

drop policy if exists "GOTM admin delete" on public.game_of_the_month;
create policy "GOTM admin delete" on public.game_of_the_month for delete to authenticated
using (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role='Admin'));
