import {requireAdmin,rest,authAdmin,logAudit,sendError} from './_auth.js'
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'POST only'});try{const {user,service}=await requireAdmin(req),b=req.body||{},a=b.action
 if(a==='list'){const au=await authAdmin(service,'users?page=1&per_page=1000');const profiles=await rest(service,'profiles?select=id,username,role,disabled');const pm=new Map((profiles||[]).map(p=>[p.id,p]));return res.json({users:(au.users||[]).map(u=>({...pm.get(u.id),id:u.id,email:u.email||''}))})}
 if(a==='create'){if(!b.username||!b.email||String(b.password||'').length<6)throw Error('Username, email, and a 6+ character password are required.');const out=await authAdmin(service,'users',{method:'POST',body:{email:b.email,password:b.password,email_confirm:true,user_metadata:{username:b.username}}});await rest(service,'profiles',{method:'POST',body:{id:out.id,username:b.username,role:'Runner',disabled:false},prefer:'resolution=merge-duplicates,return=minimal'});await logAudit(service,user.id,'ADD_USER',b.username);return res.json({ok:true})}
 const id=b.userId;if(!id)throw Error('userId is required.');if(id===user.id&&['delete','toggleDisabled'].includes(a))throw Error('You cannot disable or remove your own logged-in Admin account.')
 const p=(await rest(service,`profiles?id=eq.${encodeURIComponent(id)}&select=id,username,role,disabled`))?.[0];if(!p)throw Error('User not found.')
 if(a==='toggleDisabled'){await rest(service,`profiles?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:{disabled:!p.disabled},prefer:'return=minimal'});await logAudit(service,user.id,'TOGGLE_USER',p.username);return res.json({ok:true})}
 if(a==='resetPassword'){if(String(b.password||'').length<6)throw Error('Use at least 6 characters.');await authAdmin(service,`users/${id}`,{method:'PUT',body:{password:b.password}});await logAudit(service,user.id,'RESET_PASSWORD',p.username);return res.json({ok:true})}
 if(a==='changeRole'){if(!['Runner','Moderator','Admin'].includes(b.role))throw Error('Role must be Runner, Moderator, or Admin.');if(id===user.id&&b.role!=='Admin')throw Error('You cannot demote your own active Admin account.');await rest(service,`profiles?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:{role:b.role},prefer:'return=minimal'});await logAudit(service,user.id,'CHANGE_ROLE',`${p.username}: ${p.role} -> ${b.role}`);return res.json({ok:true})}
 if(a==='edit'){const patch={username:b.username};if(b.email)await authAdmin(service,`users/${id}`,{method:'PUT',body:{email:b.email}});await rest(service,`profiles?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:patch,prefer:'return=minimal'});await logAudit(service,user.id,'EDIT_USER',b.username);return res.json({ok:true})}
 if(a==='delete'){for(const t of ['submissions','challenge_members','champions'])await rest(service,`${t}?user_id=eq.${encodeURIComponent(id)}`,{method:'DELETE',prefer:'return=minimal'});await rest(service,`profiles?id=eq.${encodeURIComponent(id)}`,{method:'DELETE',prefer:'return=minimal'});await authAdmin(service,`users/${id}`,{method:'DELETE'});await logAudit(service,user.id,'DELETE_USER',p.username);return res.json({ok:true})}
 throw Error('Unknown account action.')
}catch(e){sendError(res,e)}}
