import {requireAdmin,rest,logAudit,sendError} from './_auth.js'
async function recalc(service,cid){await rest(service,`champions?challenge_id=eq.${cid}`,{method:'DELETE',prefer:'return=minimal'});const games=await rest(service,`challenge_games?challenge_id=eq.${cid}&select=id`),subs=await rest(service,`submissions?challenge_id=eq.${cid}&select=user_id,challenge_game_id,time_ms`),members=await rest(service,`challenge_members?challenge_id=eq.${cid}&select=user_id`);const gids=(games||[]).map(g=>g.id),ids=new Set([...(members||[]).map(x=>x.user_id),...(subs||[]).map(x=>x.user_id)]),rows=[];for(const uid of ids){let total=0,done=0;for(const gid of gids){const vals=(subs||[]).filter(s=>s.user_id===uid&&s.challenge_game_id===gid).map(s=>Number(s.time_ms));if(vals.length){done++;total+=Math.min(...vals)}}if(gids.length&&done===gids.length)rows.push({uid,total})}if(!rows.length)return;const best=Math.min(...rows.map(r=>r.total)),winners=rows.filter(r=>r.total===best).map(r=>({challenge_id:Number(cid),user_id:r.uid,total_time_ms:r.total,awarded_at:new Date().toISOString()}));await rest(service,'champions',{method:'POST',body:winners,prefer:'return=minimal'})}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'POST only'});try{const {user,service}=await requireAdmin(req),b=req.body||{},a=b.action;if(a==='audit'){await logAudit(service,user.id,b.details?.action||'ADMIN_ACTION',b.details?.details||'');return res.json({ok:true})}
 if(a==='correctSubmission'){await rest(service,`submissions?id=eq.${b.submissionId}`,{method:'PATCH',body:{time_ms:b.timeMs},prefer:'return=minimal'});await logAudit(service,user.id,'CORRECT_TIME',`submission=${b.submissionId}, ms=${b.timeMs}`)}
 else if(a==='deleteSubmission'){await rest(service,`submissions?id=eq.${b.submissionId}`,{method:'DELETE',prefer:'return=minimal'});try{await rest(service,`submission_notes?submission_id=eq.${b.submissionId}`,{method:'DELETE',prefer:'return=minimal'})}catch{}await logAudit(service,user.id,'DELETE_SUBMISSION',`submission=${b.submissionId}`)}
 else if(a==='noteSubmission'){try{if(b.note)await rest(service,'submission_notes',{method:'POST',body:{submission_id:b.submissionId,note:b.note,admin_user_id:user.id,updated_at:new Date().toISOString()},prefer:'resolution=merge-duplicates,return=minimal'});else await rest(service,`submission_notes?submission_id=eq.${b.submissionId}`,{method:'DELETE',prefer:'return=minimal'})}catch{throw Error('Submission notes table is not installed yet. Run supabase/002_web_admin_support.sql once.')}await logAudit(service,user.id,'SUBMISSION_NOTE',String(b.submissionId))}
 else if(a==='addParticipant'){const p=(await rest(service,`profiles?username=eq.${encodeURIComponent(b.username)}&select=id,username`))?.[0];if(!p)throw Error('Runner username not found.');await rest(service,'challenge_members',{method:'POST',body:{challenge_id:b.challengeId,user_id:p.id,joined_at:new Date().toISOString()},prefer:'resolution=merge-duplicates,return=minimal'});await logAudit(service,user.id,'ADD_PARTICIPANT',p.username)}
 else if(a==='removeParticipant'){await rest(service,`submissions?challenge_id=eq.${b.challengeId}&user_id=eq.${b.userId}`,{method:'DELETE',prefer:'return=minimal'});await rest(service,`challenge_members?challenge_id=eq.${b.challengeId}&user_id=eq.${b.userId}`,{method:'DELETE',prefer:'return=minimal'});await rest(service,`champions?challenge_id=eq.${b.challengeId}&user_id=eq.${b.userId}`,{method:'DELETE',prefer:'return=minimal'});await logAudit(service,user.id,'REMOVE_PARTICIPANT',b.userId)}
 else if(a==='extendChallenge'){const c=(await rest(service,`challenges?id=eq.${b.challengeId}&select=ends_at`))?.[0];if(!c?.ends_at)throw Error('Challenge timer has not started.');const end=new Date(new Date(c.ends_at).getTime()+Number(b.days)*86400000);await rest(service,`challenges?id=eq.${b.challengeId}`,{method:'PATCH',body:{ends_at:end.toISOString()},prefer:'return=minimal'});await logAudit(service,user.id,'EXTEND_CHALLENGE',`${b.days} days`)}
 else if(a==='endChallenge'){const now=new Date().toISOString();await rest(service,`challenges?id=eq.${b.challengeId}`,{method:'PATCH',body:{status:'Complete',ends_at:now,completed_at:now},prefer:'return=minimal'});await recalc(service,b.challengeId);await logAudit(service,user.id,'END_CHALLENGE_NOW','')}
 else if(a==='editChallenge'){await rest(service,`challenges?id=eq.${b.challengeId}`,{method:'PATCH',body:{name:b.name,ends_at:b.endsAt},prefer:'return=minimal'});await logAudit(service,user.id,'EDIT_CHALLENGE_SETTINGS',b.name)}
 else if(a==='reopenChallenge'){await rest(service,`challenges?id=eq.${b.challengeId}`,{method:'PATCH',body:{status:'Active',completed_at:null},prefer:'return=minimal'});await rest(service,`champions?challenge_id=eq.${b.challengeId}`,{method:'DELETE',prefer:'return=minimal'});await logAudit(service,user.id,'REOPEN_CHALLENGE','')}
 else if(a==='recalculate'){await recalc(service,b.challengeId);await logAudit(service,user.id,'RECALCULATE_STANDINGS','')}
 else throw Error('Unknown admin action.');return res.json({ok:true})}catch(e){sendError(res,e)}}
